// This file was generated by Dashcode from Apple Inc.
// You may edit this file to customize your Dashboard widget.

function loadPreferences(key) {
	return widget.preferenceForKey(widget.identifier + "-" + key);
}

function savePreferences(key, value) {
	widget.setPreferenceForKey(value, widget.identifier + "-" + key);
}

function parseEvents(events) {
    var outputHTML = "";
    var splitdate = "";
    var baseurl = "http://www.mtbcalendar.com/events/";
    var eventTemplate = new Template('#{newDate}: <span onclick=\'widget.openURL("#{calendarURL}")\'>#{name}</span> (#{state})<br />');

    events.each(function(event) {
        splitdate = event.start_date.split("/");
        event.newDate = splitdate[1]+'/'+splitdate[2]+'/'+splitdate[0].replace(/^20/,""); // gives us 01/15/09 format
		event.calendarURL = baseurl + event.id + '-' + event.permalink;
        outputHTML += eventTemplate.evaluate(event);         
    });

	// updating scrollarea
	$("content").innerHTML = outputHTML;
	$("scrollArea").object.refresh();
}

// Called when an XMLHttpRequest loads a feed; works with the XMLHttpRequest setup snippet
function xmlLoaded(xmlRequest) 
{
	if (xmlRequest.status == 200) {
		events = ( "(" + xmlRequest.responseText + ")" ).evalJSON();
		parseEvents(events);
	}
	else {
		alert("Error fetching data: HTTP status " + xmlRequest.status);
	}
}

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
function load()
{
    setupParts();
	if (feedURL == "") {
		savePreferences("region", "http://www.mtbcalendar.com/tags/norcal.json?future=1");
		feedURL = loadPreferences("region");
        popup.value = feedURL;
	}
    xmlLoaded(xmlRequest);
    xmlRequest.onload = onloadHandler;
    xmlRequest.open("GET", feedURL);
    xmlRequest.setRequestHeader("Cache-Control", "no-cache");
    xmlRequest.send(null);
}

//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{
    // Stop any timers to prevent CPU usage
    // Remove any preferences as needed
    // widget.setPreferenceForKey(null, createInstancePreferenceKey("your-key"));
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{
    // Stop any timers to prevent CPU usage
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{
    // Restart any timers that were stopped on hide
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{
    // Retrieve any preference values that you need to be synchronized here
    // Use this for an instance key's value:
    // instancePreferenceValue = widget.preferenceForKey(null, createInstancePreferenceKey("your-key"));
    //
    // Or this for global key's value:
    // globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

//
// Function: showBack(event)
// Called when the info button is clicked to show the back of the widget
//
// event: onClick event from the info button
//
function showBack(event)
{
    var front = $("front");
    var back = $("back");

    if (window.widget) {
        widget.prepareForTransition("ToBack");
    }

    popup.value = loadPreferences("region");

    front.style.display = "none";
    back.style.display = "block";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

//
// Function: showFront(event)
// Called when the done button is clicked from the back of the widget
//
// event: onClick event from the done button
//
function showFront(event)
{
    var front = $("front");
    var back = $("back");

    if (popup.value) {
        savePreferences("region", popup.value);
    }

    if (popup.value != feedURL)  {
        feedURL = loadPreferences("region");
        xmlLoaded(xmlRequest);
        xmlRequest.onload = onloadHandler;
        xmlRequest.open("GET", feedURL);
        xmlRequest.setRequestHeader("Cache-Control", "no-cache");
        xmlRequest.send(null);
    }
    
    if (window.widget) {
        widget.prepareForTransition("ToFront");
    }

    front.style.display="block";
    back.style.display="none";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

if (window.widget) {
    widget.onremove = remove;
    widget.onhide = hide;
    widget.onshow = show;
    widget.onsync = sync;
}

// on first load, set preference and popup to "norcal" 
var feedURL = "";
var onloadHandler = function() { xmlLoaded(xmlRequest); };
var xmlRequest = new XMLHttpRequest();
