/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "bottomRectangleShape": { "creationFunction": "CreateShape", "leftImageWidth": 12, "rightImageWidth": 12 },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "glassbutton": { "creationFunction": "CreateGlassButton", "onclick": "openWebsite", "text": "Visit MTB Calendar" },
    "glassbutton1": { "creationFunction": "CreateGlassButton", "onclick": "openRepo", "text": "v0.4" },
    "info": { "backgroundStyle": "white", "creationFunction": "CreateInfoButton", "foregroundStyle": "black", "frontID": "front", "onclick": "showBack" },
    "regionName": { "creationFunction": "CreateText", "text": "Text" },
    "scrollArea": { "autoHideScrollbars": true, "creationFunction": "CreateScrollArea", "hasVerticalScrollbar": true, "leftMargin": 4, "scrollbarDivSize": 18, "scrollbarMargin": 6, "spacing": 4 },
    "text": { "creationFunction": "CreateText", "text": "Choose Region" },
    "text1": { "creationFunction": "CreateText", "text": "This widget pulls upcoming regional MTB racing events from the mtbcalendar.com website. It updates the calendar on 1 hour intervals. Click on any race name to open the mtbcalendar.com website and see the race details." },
    "title": { "creationFunction": "CreateText", "text": "MTB Calendar" },
    "topRectangleShape": { "creationFunction": "CreateShape", "leftImageWidth": 12, "rightImageWidth": 12 }
};
