/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done", "view": "DC.View" },
    "glassbutton": { "creationFunction": "CreateGlassButton", "onclick": "openWebsite", "text": "Visit MTBcalendar", "view": "DC.View" },
    "glassbutton1": { "creationFunction": "CreateGlassButton", "onclick": "openRepo", "text": "v1.1.1", "view": "DC.View" },
    "infobutton": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "loading": { "text": "Loading Events ...", "view": "DC.Text" },
    "regionName": { "text": "Text", "view": "DC.Text" },
    "scrollArea": { "autoHideScrollbars": true, "creationFunction": "CreateScrollArea", "hasVerticalScrollbar": true, "scrollbarDivSize": 18, "scrollbarMargin": 6, "spacing": 4 },
    "text": { "text": "Region", "view": "DC.Text" },
    "text1": { "text": "This widget displays upcoming MTB events from the mtbcalendar.com website. Click on any race name to see complete race details.", "view": "DC.Text" },
    "title": { "text": "MTB", "view": "DC.Text" },
    "title1": { "text": "calendar", "view": "DC.Text" },
    "topRectangleShape": { "creationFunction": "CreateShape", "leftImageWidth": 12, "rightImageWidth": 12, "view": "DC.View" }
};










